services:
  gravtest-service:
    image: gravtest:0.2
    env_file: .env
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - ./db_init/init_mock.sql:/docker-entrypoint-initdb.d/init_mock.sql
